config/routes.rb
MalaiNabirseu::Application.routes.draw do
  get "donates/index"

  get "donates/sponser"
  
  get "donates/create"

  get "main/index"

  get "news_events/news_details"

  get "news_events/events_details"
	
	get "news_events/news"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "pages/events"

  get "pages/children"

  get "pages/who_we_are"

  get "pages/what_we_do"

  get "pages/how_to_help"

  get "pages/donate"

  get "pages/index"

  get "pages/new"

  get "pages/show"

  get "pages/get_involved"

  get "pages/create"

  get "pages/update"

  get "pages/about_us"

  get "pages/site_map"

  get "pages/contact"
	
	 get "pages/gallary"
	
 
 	resources :news_viewers

	resources :pages do
    collection do
      get 'news_paginator'
    end
  end
  
   match '/donates/create' => 'donates#create'
   match '/donates/sponser' => 'donates#sponser'

   root :to => 'pages#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/news_viewer.rb
class NewsViewer < ActiveRecord::Base
	
end

app/models/what_we_do.rb
class WhatWeDo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def is_a_valid_email?(email)
  # Check the number of '@' signs.
  	if email.count("@") != 1 then
    	return false
	# We can now check the email using a simple regex.
  # You can replace the TLD's at the end with the TLD's you wish
  # to accept.
  	elsif email =~ /^[a-zA-Z0-9][a-zA-Z0-9\._%\-\+]+@[a-zA-Z0-9\.\-]+\.[a-zA-Z]+$/ then
    	return true
  	else
    	return false
  	end
	end	 
end

app/controllers/donates_controller.rb
class DonatesController < ApplicationController
  def index
  end

  def create
  	if params[:name].blank? || params[:email].blank?
			redirect_to :back,  :notice => "blank"
 			elsif is_a_valid_email?(params[:email]) == false
 				redirect_to :back,  :notice => "invalid email"
 			else		
	 			UserMailer.donation_message(:input=>params)				
	 			redirect_to :back
		end
	end
  
  def sponser
  	if params[:name].blank? || params[:email].blank?
			redirect_to :back,  :notice => "blank"
 			elsif is_a_valid_email?(params[:email]) == false
 				redirect_to :back,  :notice => "invalid email"
 			else		
	 			UserMailer.sponser(:input=>params)
		 	  redirect_to:back
		end
  end  
  
end

app/controllers/news_events_controller.rb
class NewsEventsController < ApplicationController
  def news_details
		@children = ChildrenSlider.all()
		@news = News.all()
  end

  def events_details
			@children = ChildrenSlider.all()
			@news = News.all()
  end

  def news
		@children = ChildrenSlider.all()
			@news = News.all()
  end


end

app/controllers/news_viewers_controller.rb
class NewsViewersController < ApplicationController
	def create
		if params[:news_viewer][:name].blank? || params[:news_viewer][:email].blank?
			redirect_to :back,  :notice => "blank"
 			elsif is_a_valid_email?(params[:news_viewer][:email]) == false
 				redirect_to :back,  :notice => "invalid email"
 			else		
				@news_viewer =NewsViewer.create(params[:news_viewer])
				@news_viewer.save!
				redirect_to :back
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@news_viewer =NewsViewer.new()
    @news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end

  end

	def news_paginator
     @news = News.order("news_desc").page(params[:page]).per(2)
     respond_to do |format|
      format.html
      format.js
    end
  end

  def about_us
		@news_viewer =NewsViewer.new()
		@news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end
  end

  def get_involved
  	@news_viewer =NewsViewer.new()
		@news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end

  end

  def events
		@news_viewer =NewsViewer.new()
    @news_top =News.all()
    @news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end
  end

  def children
		@news_viewer =NewsViewer.new()
		@news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end

  end

  def who_we_are
  end

  def what_we_do
			@news_viewer =NewsViewer.new()
			@whatwedo = WhatWeDo.all()
			@news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end
		@news_viewer = NewsViewer.new()
	end

  def how_to_help
  end



	 def site_map
			@news_viewer =NewsViewer.new()
			@news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end

  end

	 def contact
	@news_viewer =NewsViewer.new()
			@news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end
  end

	def donate
		@news_viewer = NewsViewer.new()
		@news = News.all()
		@news	 = News.order("news_desc").page(params[:page]).per(2)
    respond_to do |format|
      format.html
      format.js
      end

		def gallary
		@news = News.all()
  	end

  end



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_events_helper.rb
module NewsEventsHelper
end

app/helpers/news_viewers_helper.rb
module NewsViewersHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_banner.html.erb
<div class="anyClass" >
<div id="logo">
</div>
   
        

          
<div id="supersize">
	<a href="#"><%=image_tag "Rashila.jpg" %></a>
	<a href="#"><%=image_tag "Sangeeta.jpg" %></a>
	<a href="#"><%=image_tag "we_All.jpg" %></a>
</div>


        
     
</div>
</div>

app/views/application/_donatepopup.html.erb
<!--popup content-->
	      <div id="popupContainer" class="hidden">
	        	<a id="close" class="hidden" title="close popup"></a>

		        <h1 class="newsletter_signup">Donation</h1>
			<div id="newsletter_text">
				<p>To give donation to this wonderful cause please fill the form below and we will contact you. Thank You </p>
			</div>
						<div class="form_block">
								<%= form_tag  ({:controller=>"donates", :action=>"create"}) do%>
							<div class="form_holder">
									<%= label_tag (:Name)%>
									<%= text_field_tag'name', nil,:class=>"form_input" %></br>
							</div>
							<div class="form_holder">
									<%= label_tag (:Email)%>
									<%= text_field_tag 'email',nil,:class=>"form_input"%></br>
							</div>
							<div class="form_holder">
									<%= label_tag (:Comment)%>
									<%= text_area_tag'comment',nil,:class=>"form_input"%></br></br>
							</div>
							<div class="form_holder">
									<%= submit_tag '',:class=>"submit_Btn"%>
							</div>
								<%end%>
				</div>


	  </div>
	       <div id="overlayEffect">
         </div>
  <!--end popup content-->

app/views/application/_footer.html.erb
<div id="footer">
	<div id="footer_content">
        <div id="main_footer">
           <div id="footer_link">
				   	<ul>
                <li><a href="/pages/about_us" class="text">About Us</a></li>
                <li><a href="/pages/children">Our Children</a></li>
                 <li><a href="/pages/about_us">Board Members</a></li>
                 <li><a href="/pages/about_us">Our History</a></li>
           </ul>
           <ul>
                <li><a href="/news_events/news" class="text">News And Events</a></li>
                <li><a href="/pages/events">Latest News</a></li>
                 <li><a href="/pages/events">Upcoming Events</a></li>

           </ul>
           <ul>
                <li ><a href="/pages/get_involved" class="text">How You Can Help</a></li>
                <li><a href="/pages/get_involved">Compaign</a></li>
                 <li><a href="/pages/get_involved">Volunteer</a></li>
                 <li><a href="/pages/get_involved">Fundraise</a></li>
								<li><a href="/pages/donate">Donate</a></li>
           </ul>

           </div>
           <div id="social_network">
            <a class="facebook" target="_blank" href="http://www.facebook.com/pages/Malai-Na-Birseu-Bal-Griha/155262331260057"></a>
<a class="twitter"  target="_blank" href="#"></a>

           </div>
				</div>	 <!--end of main_footer-->

  </div>	 <!--end of main_content-->
<div id="copyright_footer">
       <div id="sub_footer">
             <div id="powered_by">
                  <span style="float:left;">Powered By: </span><a href="http://www.revol-tech.com.np">Revol-Tech Nepal</a>
              </div>	 <!--end of powered_by-->
              <div id="owner">
                   <span>&copy;2012 Malai Nabirseu Bal Griha</span>
              </div>		<!--end of owner-->
              <div id ="contact">

                    <div class="site">
                         <%= image_tag "arrow_Icon.png",:class=>"img"  %>
                          <span> <a href="/pages/site_map">Site Map</a></span>
                    </div>	<!--end of site-->
                    <div class="site">
                      <%= image_tag "arrow_Icon.png",:class=>"img"  %></a>
                              <span><a href="/pages/contact">Contact</a></span>
                    </div>	<!--end of site-->

      			 </div>		<!--end of contact-->
			</div>	<!--end of sub_footer-->
</div>	<!--end of copyright_footer-->
</div>	<!--end of footer-->

app/views/application/_get_involved.html.erb
				<div id="get_involved">
							<div id="get_involved_content">
									<div class="get_involved_title">
											<%= image_tag "getinvolvedTitle.png" %>

									</div>	<!--end of get_involved_title-->
									<div id="get_involved_image">
										<div id="get_involved_text">
											<p>YOUR SUPPORT MEANS WE CAN HELP THE NEPAL'S MOST VULNERABLE AND NEGLECTED CHILDREN AND YOUNG PEOPLE</P>
										</div>		<!--end of get_involved_text-->
									<div class="get_involved_by">

	<div id="wrap">

	<div id='content'>
 	<a href="#"	class="signup" id="button"></a>

		</div>
</div>
<%= render 'newsletter'%>



										<a href="/pages/get_involved" class="campaign" ></a>

										<a href="/pages/get_involved" class="volunteer" ></a>


										<a href="donate"  class="donate" ></a>

									</div>		<!--end of get_involved_by-->
									</div>		<!--get_involved_image-->
							</div>	<!--end of get_involved_content-->
				</div>		<!--end of get_involved-->

app/views/application/_image_slider.html.erb
<div id="image_slider">
	<div id="children_slider">

        <div class="prev1">

                  <a class="previous_image" href="#"></a>

							<div class="button_border">
							</div>
				</div>

				<div id="children">

            <ul class="resize">
                <li><%=image_tag"Alisha.png", :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Alisha</strong><h2>Age:11 </br>Class:4</br>Ambition:Actor</br>Hobby:Playing, Dancing and Singing</h2></a></span>
                </li>
                <li><%=image_tag"Anita.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Anita</strong><h2>Age:12 </br>Class:3</br>Ambition:Artist and Painting</br>Hobby:Painting and Playing with dolls</h2></a></span>
                </li>
                <li><%=image_tag"Babita.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Babita</strong><h2>Age:10 </br>Class:3</br>Ambition:Singer</br>Hobby:Singing and Reading story books</h2></a></span>
                </li>
                <li><%=image_tag"Barme.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Barme</strong><h2>Age:13 </br>Class:5</br>Ambition:Dancer</br>Hobby:Games Playing and Story books reading</h2></a></span>
                </li>
                <li><%=image_tag"basundhara.png", :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Basundhara</strong><h2>Age:13 </br>Class:5</br>Ambition:Artist and Lawyer</br>Hobby:Reading books, Playing games and Painting</h2></a></span>
                </li>
                <li><%=image_tag"devaki.png", :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Devaki</strong><h2>Age:14 </br>Class:9</br>Ambition:Nursing</br>Hobby:Reading story books, Playing games and Listening music</h2></a></span>
                </li>
                <li><%=image_tag"dikshya.png", :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Dikshya</strong><h2>Age:16 </br>Class:9</br>Ambition:Chef</br>Hobby:Cooking, Painting and Singing</h2></a></span>
                </li>
                <li><%=image_tag"jamuna.png" , :class=>"slide" %>
										 <span class='imgname'><a href="/pages/children"><strong>Jamuna</strong><h2>Age:10 </br>Class:2</br>Ambition:Chroregrapher</br>Hobby:Likes studing books</h2></a></span></li>
								<li><%=image_tag"junu.png" , :class=>"slide" %>
										 <span class='imgname'><a href="/pages/children"><strong>Junu</strong><h2>Age:9 </br>Class:1</br>Ambition:Chroregrapher</br>Hobby:Dancing and playing with music</h2></a></span></li>
								<li><%=image_tag"kabita.png" , :class=>"slide" %>
											 <span class='imgname'><a href="/pages/children"><strong>Kabita</strong><h2>Age:12 </br>Class:4</br>Ambition:Singer</br>Hobby:Listening music, Singing and Dancing</h2></a></span></li>
								<li><%=image_tag"namrata.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Namrata</strong><h2>Age:14 </br>Class:5</br>Ambition:Hotel Manager</br>Hobby:Reading books and Listening music</h2></a></span>
									 </li>
								<li><%=image_tag"rabina.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Rabina</strong><h2>Age:14 </br>Class:5</br>Ambition:Singer and Dancer</br>Hobby:Dancing and singing</h2></a></span></li>
								<li><%=image_tag"rashila.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Rashila</strong><h2>Age:12 </br>Class:4</br>Ambition:Air-hostess and Fashion Designer</br>Hobby:Painting and Reading</h2></a></span>
									 </li>
								<li><%=image_tag"runa.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Runa</strong><h2>Age:14 </br>Class:7</br>Ambition:Chroregrapher</br>Hobby:Novel reading, Adventure visits and Watching cartoon</h2></a></span>
									 </li>
								<li><%=image_tag"sangita.png" , :class=>"slide" %></a>
                  <span class='imgname'><a href="/pages/children"><strong>Sangita</strong><h2>Age:9 </br>Class:3</br>Ambition:Artist</br>Hobby:Playing games(cricket, Basketball, Skipping and Badminton)</h2></a></span>
									 </li>
							<li><%=image_tag"sarita.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Sarita</strong><h2>Age:12 </br>Class:3</br>Ambition:Singer</br>Hobby:Playing games, Reading and Writing story</h2></a></span>
									 </li>
							<li><%=image_tag"sita.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Sita</strong><h2>Age:13 </br>Class:5</br>Ambition:Hotel Manager</br>Hobby:To study, Playing and Cooking</h2></a></span>
									 </li>
							<li><%=image_tag"sunita.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Sunita</strong><h2>Age:13 </br>Class:5</br>Ambition:Artist and Beautician</br>Hobby:Dancing and Painting</h2></a></span>
									 </li>
						<li><%=image_tag"goma.png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Goma</strong><h2>Age:13 </br>Class:6</br>Ambition:Artist</br>Hobby:Dancing, Painting and Cooking</h2></a></span>
									 </li>
						<li><%=image_tag"gyanu (2).png" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Gyanu</strong><h2>Age:9 </br>Class:3</br>Ambition:Air-hostess</br>Hobby:Playing, Painting and Reading</h2></a></span>
									 </li>
						<li><%=image_tag"alisha.jpg" , :class=>"slide" %>
                  <span class='imgname'><a href="/pages/children"><strong>Gyanu</strong><h2>Age:17 </br>Class:Nursing</br>Ambition:Nurse</br>Hobby:Singing and Listening music</h2></a></span>
									 </li>
             </ul>

				</div>

				<div class="next1">

								<a class="next_image"  style= "float:right;" href="#"></a>

							<div class="button_border"  style= "float:left;">
							</div>
				</div>

	 </div>		<!--end of children_slider-->

</div>		<!--end of image_slider-->	

app/views/application/_lowercontent.html.erb
<div id="lower_content">
     <div id="sub_lower_content">
<div class="low_block_1">

 <%= render 'news_display' %>
<%= render 'get_involved'%>

<div class="add_block">
		<div class="add_block_content1">
				<%= image_tag "malainabirseu_Logo.png",:class=>"logopng" %>
				
			<div class="read_more">	</div>

		</div>
		<div class="add_block_content2">

		<%= image_tag "banner-copy.png" %>
		</div>
		<div class="add_block_content3">
				<div id="map_canvas" style="width:201px; height:248px;"></div>

		</div>
</div>
</div>

<div id="facebook_like">
							<div class="fb_image">
									<%= image_tag "likefbtittle.png" %>
							</div>
              <div id="facebook_content">

<iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FMalieNaBirseu%2F155262331260057&amp;width=310&amp;height=558&amp;colorscheme=light&amp;show_faces=true&amp;border_color=%23cfcfcf&amp;stream=true&amp;header=false" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:310px; height:558px;" allowTransparency="true"></iframe>
              </div>
				 </div>


</div>
</div>

app/views/application/_navigation.html.erb
<div id="navigation">

   <div id="navigation_content">
               <div id="main_nav">
									<div style="float:right; display:block; width:170px; margin:21px 0 0 0;">
<a href="/pages/donate"><div class="nav_donate_Btn"></div></a>
<div id="sub_nav">
									<ul>
										<li><a href="/pages/contact"><span>contact us</span></a></li>
<li><a href="/pages/gallary"><span>gallery</span></a></li>
									</ul>
							</div>
</div>
                     <div id="nav">
											<ul class="sidebar_content">
                     				<li>

																	<a href="/pages/index"><span>home</span></a></li>
										 							<li><a href="/pages/about_us"><span>about us</span></a></li>
										 							<li><a href="/pages/get_involved"><span>get involved</span></a></li>
																	<li><a href="/pages/children"><span>children</span></a></li>
										 							<li><a href="/pages/events"><span>events</span></a></li>
										 							
																	<li><a href="/pages/what_we_do" style="margin:0px;"><span>what we do</span></a></li>

								      	</ul>

													
							      	</div>	<!--end of nav-->

<a href="/pages/index"><%= image_tag "malainabirseu_Logo.png", :id=>"logo" %></a>
                      <a href="/pages/index">  <%= image_tag "malai_logo.png",:class=>"title_img"%></a>


        	 </div><!--end of main_nav-->
							
	   </div>
</div>  

app/views/application/_newsletter.html.erb
<!--popup content-->
<% if flash[:notice] == "blank"%>
	<script type="text/javascript">
		$(document).ready(function(){
			alert("Please fill the form completely!!!")
		});
	</script>	
<%end%>
<% if flash[:notice] == "invalid email"%>
	<script type="text/javascript">
		$(document).ready(function(){
			alert("Pease check your email address and try again!")
		});
	</script>	
<%end%>
 <div id="popupContainer" class="hidden">
	        	<a id="close" class="hidden" title="close popup"></a>
		         <h1 class="newsletter_signup">Newsletter Signup</h1>
			<div id="newsletter_text">
				<p>Please sign-up to get the latest news</p>
			</div>
						<div class="form_block">
								<%= form_for @news_viewer do |t|%>
								<div class="form_holder">
								    <label for="name">Name :</label>
										<%= t.text_field 'name',:class=>"form_input" %>
								</div>
								<div class="form_holder">
										<label for="email">Email :</label>
										<%= t.text_field 'email',:class=>"form_input" %>
							</div>
						<div class="form_holder">

									<%= t.submit '',:class=>"submit_Btn"%>
									
						</div>
						<%end%>
				</div>
                   
                  
	  </div>
	       <div id="overlayEffect">
         </div>
  <!--end popup content-->

app/views/application/_sponsorpopup.html.erb
<!--popup content-->
	      <div id="popupContainers" class="hidden">
	        	<a id="closes" class="hiddens" title="closes popup"></a>
		         <h1 class="newsletter_signup">sponsor</h1>
			<div id="newsletter_text">
				<p>Sponsorship is a cash and/or in-kind fee paid to a property (typically in sports, arts, entertainment or causes) in return for access to the exploitable commercial potential associated with that property, according to IEG.

While the sponsee (property being sponsored) may be nonprofit, unlike philanthropy, sponsorship is done with the expectation of a commercial return.</p>
			</div>
						<div class="form_block">
								<%= form_tag  ({:controller=>"donates", :action=>"sponser"}) do%>
								<div class="form_holder">
									<%= label_tag (:Name)%>
									<%= text_field_tag'name',nil,:class=>"form_input" %></br>
								</div>
								<div class="form_holder">
									<%= label_tag (:Email)%>
									<%= text_field_tag 'email',nil,:class=>"form_input"%></br>
								</div>
								<div class="form_holder">
									<%= label_tag (:Comment)%>
									<%= text_area_tag'comment',nil,:class=>"form_input"%></br></br>
								</div>
								<div class="form_holder">
									<%= submit_tag '',:class=>"submit_Btn"%>
								</div>		
								<%end%>
				</div>


	  </div>
	       <div id="overlayEffects">
         </div>
  <!--end popup content-->

app/views/donates/deliver.html.erb
<h1>Donates#deliver</h1>
<p>Find me in app/views/donates/deliver.html.erb</p>

app/views/donates/index.html.erb
<h1>Donates#index</h1>
<p>Find me in app/views/donates/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MalaiNabirseu</title>

<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

<link rel="shortcut icon" href="/images/favIcon.png"/>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= stylesheet_link_tag    "application","banner","aboutus","children","style","site_map","slidersized","footer","image_slider","lower_content","gallary","get_involved","navigation","news","news_events","pages","uppercontent","events","donate","contact","what_we_do" %>

<%= favicon_link_tag "favIcon.ico" %>
  <%= javascript_include_tag "application" %>



  <%= csrf_meta_tags %>




</head>
<body  onload="initialize()">

<%= yield %>


</body>
</html>

app/views/pages/home.html.erb
		<div id="main_wrapper">
         <div id="banner">
					
            <div id="wrapper">
               <div id="main_nav">
									<%= image_tag "donate.png",:class=>"donate_img"%>
                     <div id="nav">
												<ul>
                     				<li><%= link_to "Home",pages_home_path  %></li>
										 				<li><%= link_to "about us",pages_about_us_path  %></li>
										 				<li><%= link_to "get involved",pages_get_involved_path %></li>
										 				<li><%= link_to "events",pages_events_path  %></li>
										 				<li><%= link_to "chidren",pages_children_path  %></li>
								      	</ul>
							      	</div>	<!--end of nav-->		
                            <%= image_tag "logo_title.png",:class=>"title_img"%>
										
             	 </div><!--end of main_nav-->
									<div id="title">
											<%= image_tag "title.png",:id=>"mnbg" %>
															<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacinia luctus libero quis hendrerit.
															 Vivamus faucibus orci malesuada nunc viverra mattis. Nunc vel aliquet urna. Maecenas pharetra orci sed dolor gravida </p>
									</div>   <!--end of title-->
              
				</div>       <!--end of wrapper-->
			</div>    <!--end of banner-->
        <div id="main_content">
			    	<div id="content">
											<div class="sub_content">
															<div class="color_red">
															</div>
																		<%= image_tag "who.png",:class=>"content_title" %>
																	<%= image_tag "children-alisha.jpg",:class=>"content_image" %>
											<div class="content_text">
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacinia luctus libero quis hendrerit.
															 Vivamus faucibus orci malesuada nunc viverra mattis. Nunc vel aliquet urna. Maecenas pharetra orci sed dolor gravida </p>
	
              				</div>	<!--end of content_text-->
			 								</div>	 <!--end of sub_content-->
 						</div>	 <!--end of content-->	
						<div id="content">
											<div class="sub_content">
													<div class="color_blue">
													</div>
														<%= image_tag "what.png",:class=>"content_title" %>
																				<%= image_tag "children-alisha.jpg",:class=>"content_image" %>
											<div class="content_text">
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacinia luctus libero quis hendrerit.
															 Vivamus faucibus orci malesuada nunc viverra mattis. Nunc vel aliquet urna. Maecenas pharetra orci sed dolor gravida </p>
	
              				</div>		<!--end of content_text-->	
 											</div>	 <!--end of sub_content-->
 					</div>	<!--end of content-->		
					<div id="content">
										<div class="sub_content">
													<div class="color_yellow">
													</div>
														<%= image_tag "how.png",:class=>"content_title" %>
                           <%= image_tag "children-alisha.jpg",:class=>"content_image" %>
																	
										<div class="content_text">
                     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacinia luctus libero quis hendrerit.
															 Vivamus faucibus orci malesuada nunc viverra mattis. Nunc vel aliquet urna. Maecenas pharetra orci sed dolor gravida </p>
	
             			 </div>	<!--end of content_text-->	
 									 </div>	<!--end of content_text-->	
 					</div>	<!--end of content-->	
    </div>		<!--end of main_content-->	
					<div id="image_slider">
            <div id="children">
								<%= image_tag "children-alisha.jpg",:class=>"child_image" %>
<%= image_tag "children-alisha.jpg",:class=>"child_image" %>
<%= image_tag "children-alisha.jpg",:class=>"child_image" %>
<%= image_tag "children-alisha.jpg",:class=>"child_image" %>
<%= image_tag "children-alisha.jpg",:class=>"child_image" %>
    </div>           
					</div>
		</div>     <!--end of main_wrapper-->		

app/views/pages/how_to_help.html.erb
 <%= render 'navigation'%>

app/views/pages/index.html.erb
<div id="main_wrapper">
      <%= render 'navigation'%>
      <%= render 'banner'%>
	 	  <%= render 'uppercontent'%>
			<%= render 'image_slider'%>
		  <%= render 'lowercontent'%>
 			<%= render 'footer'%>
 </div>